workflows:
  ios-release:
    name: iOS App Store Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: ru.smit34.smitBilling
      flutter: 3.24.5
      xcode: 16.2
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Remove alpha from icons
        script: |
          for f in ios/Runner/Assets.xcassets/AppIcon.appiconset/*.png; do
            sips -s format bmp "$f" --out /tmp/icon_tmp.bmp >/dev/null 2>&1
            sips -s format png /tmp/icon_tmp.bmp --out "$f" >/dev/null 2>&1
          done
      - name: Flutter build ipa
        script: flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
